### ISSUE TITLE
[Task] Get stats about download lenra_cli from Github and Cargo

### ISSUE THREAD

**Issue by shiipou** [lenra-io/app-stat-us#9]
## What should be done 
Create a Lenra app to get stats about download app.

## Technical recommandation
Must show stats aggregated stats per version or/and in total using lenra crons to check downloads number from Github API and Cargo api.

EDIT: We can implement this functionnality directly in the [app-stat-us](https://github.com/lenra-io/app-stat-us)

**Comment by taorepoara** [comment]
Duplicates https://github.com/lenra-io/lenra_cli/issues/271
